### ISSUE TITLE
Failed on stacker link

### ISSUE THREAD

**Issue by martylouis** [StackerHQ/stacker-cli#18]
Just installed, maybe im missing something. Getting a command failed on `stacker link`, looks like `.bin/hostile` doesn't exist. 

Here's a screenshot »

![image](https://cloud.githubusercontent.com/assets/169188/24249332/d3e5b908-0fa0-11e7-8f20-f519cc77614c.png)

**Comment by deiucanta** [comment]
@martylouis thanks for reporting

It seems that `hostile` is a dependency of `stacker-core` but NPM flattens all the dependencies into a single `node_modules` directory.

I'm looking for the proper way to find the path regardless if `stacker-core` runs on it's own or a dependency in some other packages. Will get back to you soon :)

**Comment by deiucanta** [comment]
I fixed it and released a new version of `stacker-core`. Try the following

```
npm uninstall -g stacker-cli
npm install -g stacker-cli
stacker unlink
stacker link
```

**Comment by martylouis** [comment]
@deiucanta Awesome, install works, thanks for the quick fix!
